import type { LeagueStandings, PlayerStats } from '@/types';

// Mock league standings data
const mockPlayers: PlayerStats[] = [
  {
    userId: 'user-001',
    name: 'Sarah Johnson',
    played: 15,
    won: 10,
    drawn: 3,
    lost: 2,
    goalsFor: 28,
    goalsAgainst: 12,
    goalDifference: 16,
    points: 33,
    rank: 1,
  },
  {
    userId: 'user-002',
    name: 'Michael Chen',
    played: 15,
    won: 10,
    drawn: 2,
    lost: 3,
    goalsFor: 25,
    goalsAgainst: 13,
    goalDifference: 12,
    points: 32,
    rank: 2,
  },
  {
    userId: 'mock-user-123', // This is our logged-in mock user
    name: 'John Doe',
    played: 15,
    won: 9,
    drawn: 4,
    lost: 2,
    goalsFor: 24,
    goalsAgainst: 14,
    goalDifference: 10,
    points: 31,
    rank: 3,
  },
  {
    userId: 'user-004',
    name: 'Emily Rodriguez',
    played: 15,
    won: 8,
    drawn: 5,
    lost: 2,
    goalsFor: 22,
    goalsAgainst: 11,
    goalDifference: 11,
    points: 29,
    rank: 4,
  },
  {
    userId: 'user-005',
    name: 'David Thompson',
    played: 15,
    won: 8,
    drawn: 4,
    lost: 3,
    goalsFor: 21,
    goalsAgainst: 15,
    goalDifference: 6,
    points: 28,
    rank: 5,
  },
  {
    userId: 'user-006',
    name: 'Jessica Martinez',
    played: 15,
    won: 7,
    drawn: 6,
    lost: 2,
    goalsFor: 19,
    goalsAgainst: 13,
    goalDifference: 6,
    points: 27,
    rank: 6,
  },
  {
    userId: 'user-007',
    name: 'James Wilson',
    played: 15,
    won: 7,
    drawn: 4,
    lost: 4,
    goalsFor: 20,
    goalsAgainst: 16,
    goalDifference: 4,
    points: 25,
    rank: 7,
  },
  {
    userId: 'user-008',
    name: 'Amanda Brown',
    played: 15,
    won: 6,
    drawn: 6,
    lost: 3,
    goalsFor: 18,
    goalsAgainst: 15,
    goalDifference: 3,
    points: 24,
    rank: 8,
  },
  {
    userId: 'user-009',
    name: 'Robert Davis',
    played: 15,
    won: 6,
    drawn: 5,
    lost: 4,
    goalsFor: 17,
    goalsAgainst: 16,
    goalDifference: 1,
    points: 23,
    rank: 9,
  },
  {
    userId: 'user-010',
    name: 'Lisa Anderson',
    played: 15,
    won: 5,
    drawn: 7,
    lost: 3,
    goalsFor: 16,
    goalsAgainst: 14,
    goalDifference: 2,
    points: 22,
    rank: 10,
  },
  {
    userId: 'user-011',
    name: 'Christopher Lee',
    played: 15,
    won: 5,
    drawn: 5,
    lost: 5,
    goalsFor: 15,
    goalsAgainst: 17,
    goalDifference: -2,
    points: 20,
    rank: 11,
  },
  {
    userId: 'user-012',
    name: 'Michelle Taylor',
    played: 15,
    won: 4,
    drawn: 6,
    lost: 5,
    goalsFor: 14,
    goalsAgainst: 18,
    goalDifference: -4,
    points: 18,
    rank: 12,
  },
  {
    userId: 'user-013',
    name: 'Daniel Garcia',
    played: 15,
    won: 4,
    drawn: 4,
    lost: 7,
    goalsFor: 13,
    goalsAgainst: 21,
    goalDifference: -8,
    points: 16,
    rank: 13,
  },
  {
    userId: 'user-014',
    name: 'Rachel White',
    played: 15,
    won: 3,
    drawn: 5,
    lost: 7,
    goalsFor: 11,
    goalsAgainst: 22,
    goalDifference: -11,
    points: 14,
    rank: 14,
  },
  {
    userId: 'user-015',
    name: 'Kevin Harris',
    played: 15,
    won: 2,
    drawn: 6,
    lost: 7,
    goalsFor: 10,
    goalsAgainst: 23,
    goalDifference: -13,
    points: 12,
    rank: 15,
  },
];

// Simulate API delay
const delay = (ms: number) => new Promise(resolve => setTimeout(resolve, ms));

export const mockLeagueService = {
  getStandings: async (currentUserId: string): Promise<LeagueStandings> => {
    console.log('[MOCK LEAGUE] Getting standings for user:', currentUserId);

    // Simulate network delay
    await delay(300);

    return {
      players: mockPlayers,
      currentUserId,
    };
  },
};
