import type { LeagueStandings, StandingEntry } from '@/types';

// Mock league standings data
const mockPlayers: StandingEntry[] = [
  {
    position: 1,
    rank: 1,
    userId: 'user-001',
    userName: 'Sarah Johnson',
    totalPoints: 33,
    picksMade: 15,
    wins: 10,
    draws: 3,
    losses: 2,
    goalsFor: 28,
    goalsAgainst: 12,
    goalDifference: 16,
  },
  {
    position: 2,
    rank: 2,
    userId: 'user-002',
    userName: 'Michael Chen',
    totalPoints: 32,
    picksMade: 15,
    wins: 10,
    draws: 2,
    losses: 3,
    goalsFor: 25,
    goalsAgainst: 13,
    goalDifference: 12,
  },
  {
    position: 3,
    rank: 3,
    userId: 'mock-user-123', // This is our logged-in mock user
    userName: 'John Doe',
    totalPoints: 31,
    picksMade: 15,
    wins: 9,
    draws: 4,
    losses: 2,
    goalsFor: 24,
    goalsAgainst: 14,
    goalDifference: 10,
  },
  {
    position: 4,
    rank: 4,
    userId: 'user-004',
    userName: 'Emily Rodriguez',
    totalPoints: 29,
    picksMade: 15,
    wins: 8,
    draws: 5,
    losses: 2,
    goalsFor: 22,
    goalsAgainst: 11,
    goalDifference: 11,
  },
  {
    position: 5,
    rank: 5,
    userId: 'user-005',
    userName: 'David Thompson',
    totalPoints: 28,
    picksMade: 15,
    wins: 8,
    draws: 4,
    losses: 3,
    goalsFor: 21,
    goalsAgainst: 15,
    goalDifference: 6,
  },
  {
    position: 6,
    rank: 6,
    userId: 'user-006',
    userName: 'Jessica Martinez',
    totalPoints: 27,
    picksMade: 15,
    wins: 7,
    draws: 6,
    losses: 2,
    goalsFor: 19,
    goalsAgainst: 13,
    goalDifference: 6,
  },
  {
    position: 7,
    rank: 7,
    userId: 'user-007',
    userName: 'James Wilson',
    totalPoints: 25,
    picksMade: 15,
    wins: 7,
    draws: 4,
    losses: 4,
    goalsFor: 20,
    goalsAgainst: 16,
    goalDifference: 4,
  },
  {
    position: 8,
    rank: 8,
    userId: 'user-008',
    userName: 'Amanda Brown',
    totalPoints: 24,
    picksMade: 15,
    wins: 6,
    draws: 6,
    losses: 3,
    goalsFor: 18,
    goalsAgainst: 15,
    goalDifference: 3,
  },
  {
    position: 9,
    rank: 9,
    userId: 'user-009',
    userName: 'Robert Davis',
    totalPoints: 23,
    picksMade: 15,
    wins: 6,
    draws: 5,
    losses: 4,
    goalsFor: 17,
    goalsAgainst: 16,
    goalDifference: 1,
  },
  {
    position: 10,
    rank: 10,
    userId: 'user-010',
    userName: 'Lisa Anderson',
    totalPoints: 22,
    picksMade: 15,
    wins: 5,
    draws: 7,
    losses: 3,
    goalsFor: 16,
    goalsAgainst: 14,
    goalDifference: 2,
  },
  {
    position: 11,
    rank: 11,
    userId: 'user-011',
    userName: 'Christopher Lee',
    totalPoints: 20,
    picksMade: 15,
    wins: 5,
    draws: 5,
    losses: 5,
    goalsFor: 15,
    goalsAgainst: 17,
    goalDifference: -2,
  },
  {
    position: 12,
    rank: 12,
    userId: 'user-012',
    userName: 'Michelle Taylor',
    totalPoints: 18,
    picksMade: 15,
    wins: 4,
    draws: 6,
    losses: 5,
    goalsFor: 14,
    goalsAgainst: 18,
    goalDifference: -4,
  },
  {
    position: 13,
    rank: 13,
    userId: 'user-013',
    userName: 'Daniel Garcia',
    totalPoints: 16,
    picksMade: 15,
    wins: 4,
    draws: 4,
    losses: 7,
    goalsFor: 13,
    goalsAgainst: 21,
    goalDifference: -8,
  },
  {
    position: 14,
    rank: 14,
    userId: 'user-014',
    userName: 'Rachel White',
    totalPoints: 14,
    picksMade: 15,
    wins: 3,
    draws: 5,
    losses: 7,
    goalsFor: 11,
    goalsAgainst: 22,
    goalDifference: -11,
  },
  {
    position: 15,
    rank: 15,
    userId: 'user-015',
    userName: 'Kevin Harris',
    totalPoints: 12,
    picksMade: 15,
    wins: 2,
    draws: 6,
    losses: 7,
    goalsFor: 10,
    goalsAgainst: 23,
    goalDifference: -13,
  },
];

// Simulate API delay
const delay = (ms: number) => new Promise(resolve => setTimeout(resolve, ms));

export const mockLeagueService = {
  getStandings: async (): Promise<LeagueStandings> => {
    console.log('[MOCK LEAGUE] Getting standings');

    // Simulate network delay
    await delay(300);

    return {
      standings: mockPlayers,
      totalPlayers: mockPlayers.length,
      lastUpdated: new Date().toISOString(),
    };
  },
};
