import type { Team } from '@/types';

// Mock Premier League teams for 2024/25 season
export const mockTeams: Team[] = [
  {
    id: 'team-001',
    name: 'Arsenal',
    shortName: 'ARS',
    code: 'ARS',
    logoUrl: 'https://resources.premierleague.com/premierleague/badges/t3.svg',
    externalApiId: 3,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'team-002',
    name: 'Aston Villa',
    shortName: 'AVL',
    code: 'AVL',
    logoUrl: 'https://resources.premierleague.com/premierleague/badges/t7.svg',
    externalApiId: 7,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'team-003',
    name: 'Bournemouth',
    shortName: 'BOU',
    code: 'BOU',
    logoUrl: 'https://resources.premierleague.com/premierleague/badges/t91.svg',
    externalApiId: 91,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'team-004',
    name: 'Brentford',
    shortName: 'BRE',
    code: 'BRE',
    logoUrl: 'https://resources.premierleague.com/premierleague/badges/t94.svg',
    externalApiId: 94,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'team-005',
    name: 'Brighton & Hove Albion',
    shortName: 'BHA',
    code: 'BHA',
    logoUrl: 'https://resources.premierleague.com/premierleague/badges/t36.svg',
    externalApiId: 36,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'team-006',
    name: 'Chelsea',
    shortName: 'CHE',
    code: 'CHE',
    logoUrl: 'https://resources.premierleague.com/premierleague/badges/t8.svg',
    externalApiId: 8,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'team-007',
    name: 'Crystal Palace',
    shortName: 'CRY',
    code: 'CRY',
    logoUrl: 'https://resources.premierleague.com/premierleague/badges/t31.svg',
    externalApiId: 31,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'team-008',
    name: 'Everton',
    shortName: 'EVE',
    code: 'EVE',
    logoUrl: 'https://resources.premierleague.com/premierleague/badges/t11.svg',
    externalApiId: 11,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'team-009',
    name: 'Fulham',
    shortName: 'FUL',
    code: 'FUL',
    logoUrl: 'https://resources.premierleague.com/premierleague/badges/t54.svg',
    externalApiId: 54,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'team-010',
    name: 'Leeds United',
    shortName: 'LEE',
    code: 'LEE',
    logoUrl: 'https://resources.premierleague.com/premierleague/badges/t2.svg',
    externalApiId: 2,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'team-011',
    name: 'Sunderland',
    shortName: 'SUN',
    code: 'SUN',
    logoUrl: 'https://resources.premierleague.com/premierleague/badges/t56.svg',
    externalApiId: 56,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'team-012',
    name: 'Liverpool',
    shortName: 'LIV',
    code: 'LIV',
    logoUrl: 'https://resources.premierleague.com/premierleague/badges/t14.svg',
    externalApiId: 14,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'team-013',
    name: 'Manchester City',
    shortName: 'MCI',
    code: 'MCI',
    logoUrl: 'https://resources.premierleague.com/premierleague/badges/t43.svg',
    externalApiId: 43,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'team-014',
    name: 'Manchester United',
    shortName: 'MUN',
    code: 'MUN',
    logoUrl: 'https://resources.premierleague.com/premierleague/badges/t1.svg',
    externalApiId: 1,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'team-015',
    name: 'Newcastle United',
    shortName: 'NEW',
    code: 'NEW',
    logoUrl: 'https://resources.premierleague.com/premierleague/badges/t4.svg',
    externalApiId: 4,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'team-016',
    name: 'Nottingham Forest',
    shortName: 'NFO',
    code: 'NFO',
    logoUrl: 'https://resources.premierleague.com/premierleague/badges/t17.svg',
    externalApiId: 17,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'team-017',
    name: 'Burnley',
    shortName: 'BUR',
    code: 'BUR',
    logoUrl: 'https://resources.premierleague.com/premierleague/badges/t90.svg',
    externalApiId: 90,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'team-018',
    name: 'Tottenham Hotspur',
    shortName: 'TOT',
    code: 'TOT',
    logoUrl: 'https://resources.premierleague.com/premierleague/badges/t6.svg',
    externalApiId: 6,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'team-019',
    name: 'West Ham United',
    shortName: 'WHU',
    code: 'WHU',
    logoUrl: 'https://resources.premierleague.com/premierleague/badges/t21.svg',
    externalApiId: 21,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'team-020',
    name: 'Wolverhampton Wanderers',
    shortName: 'WOL',
    code: 'WOL',
    logoUrl: 'https://resources.premierleague.com/premierleague/badges/t39.svg',
    externalApiId: 39,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

const delay = (ms: number) => new Promise(resolve => setTimeout(resolve, ms));

export const mockTeamsService = {
  getTeams: async (): Promise<Team[]> => {
    console.log('[MOCK TEAMS] Getting all teams');
    await delay(200);
    return mockTeams;
  },
};
